#!/bin/zsh

##########################################################
# Written by Colton Gillenwater
# Created on - 3/15/2026
##########################################################
# Script information
# Injects Netskope certificate bundle environment variables
# into the console user's shell profiles. Writes the
# variables to a dedicated ~/.netskope_vars file and adds a
# source line to ~/.zprofile and ~/.bash_profile, creating
# those files if they do not exist. Expects the cert bundle
# to already exist at the shared path produced by the cert
# bundle generation script.
##########################################################

########################################################################################
######################### CONFIGURATION ################################################
########################################################################################

# Combined PEM bundle produced by ns_build_certbundle.zsh
CERT_BUNDLE="/Users/Shared/NetskopeCertBundles/netskope-cert-bundle.pem"

# Resolve the currently logged-in console user and their home directory
MACUSER=$(/usr/sbin/scutil <<< "show State:/Users/ConsoleUser" | /usr/bin/awk '/Name :/ && ! /loginwindow/ { print $3 }')
USERHOME=$(/usr/bin/dscl . -read "/Users/$MACUSER" NFSHomeDirectory | /usr/bin/sed 's/^[^\/]*//g')

# Dedicated vars file sourced by both zprofile and bash_profile
NETSKOPE_VARS_FILE="$USERHOME/.netskope_vars"

########################################################################################
######################### USER DETECTION ###############################################
########################################################################################

# Abort if scutil returned more than one result (e.g. Fast User Switching is active)
USER_COUNT=$(echo "$MACUSER" | /usr/bin/wc -l | /usr/bin/tr -d ' ')
if [ "$USER_COUNT" -ne 1 ]; then
    echo "ERROR: Found $USER_COUNT users, expected exactly 1:"
    echo "$MACUSER"
    exit 1
fi

# Guard against an empty result from scutil
if [ -z "$MACUSER" ]; then
    echo "ERROR: MACUSER variable is empty"
    exit 1
fi

echo "Found user: $MACUSER"

########################################################################################
######################### BUNDLE VALIDATION ############################################
########################################################################################

# Abort if the bundle file is missing — this script must run after the bundle is built
if [ ! -f "$CERT_BUNDLE" ]; then
    echo "ERROR: Certificate bundle not found at $CERT_BUNDLE"
    echo "Run the cert bundle generation script first."
    exit 1
fi

# Abort if the bundle contains no certificates — an empty file would silently break TLS
CERT_COUNT=$(/usr/bin/grep -c "BEGIN CERTIFICATE" "$CERT_BUNDLE" 2>/dev/null || echo 0)
if [ "$CERT_COUNT" -eq 0 ]; then
    echo "ERROR: No certificates found in $CERT_BUNDLE"
    exit 1
fi

echo "Certificate bundle verified ($CERT_COUNT certificates)"

########################################################################################
######################### HELPER FUNCTIONS #############################################
########################################################################################

# Writes (or replaces) ~/.netskope_vars with environment variable exports that point
# each supported tool's CA trust mechanism at the Netskope bundle. The file is always
# regenerated fresh so stale paths from a previous run are never left in place.
create_netskope_vars_file() {
    local varsfile="$NETSKOPE_VARS_FILE"

    echo "Creating Netskope environment variables file: $varsfile"

    if [ -f "$varsfile" ]; then
        echo "Removing existing .netskope_vars file for clean update..."
        rm -f "$varsfile"
    fi

    cat > "$varsfile" << EOF
# Netskope Certificate Bundle Environment Variables
# Auto-generated by ns_certs_zprofile.zsh — do not manually edit

export REQUESTS_CA_BUNDLE='${CERT_BUNDLE}'  # Python/Azure CLI/Other Tools
export AWS_CA_BUNDLE='${CERT_BUNDLE}'        # AWS CLI
export SSL_CERT_FILE='${CERT_BUNDLE}'        # OpenSSL
export NODE_EXTRA_CA_CERTS='${CERT_BUNDLE}'  # Node
export CURL_CA_BUNDLE='${CERT_BUNDLE}'       # curl
export GIT_SSL_CAINFO='${CERT_BUNDLE}'       # Git
EOF

    if chown "${MACUSER}:staff" "$varsfile" 2>/dev/null && chmod 644 "$varsfile"; then
        echo "Successfully created $varsfile"
        return 0
    else
        echo "ERROR: Failed to set ownership/permissions on $varsfile"
        return 1
    fi
}

# Appends a source line for ~/.netskope_vars to the given shell rc file if one is not
# already present. Idempotent — a second run will detect the existing line and skip.
add_source_to_rcfile() {
    local rcfile="$1"
    local shell_name="$2"
    local source_line="source \"$NETSKOPE_VARS_FILE\""

    echo "Processing $shell_name file: $rcfile"

    if /usr/bin/grep -q "source.*\.netskope_vars" "$rcfile" 2>/dev/null; then
        echo "  Source line already exists in $shell_name"
    else
        echo "  Adding source line to $shell_name"
        {
            echo ""
            echo "# Source Netskope certificate bundle environment variables"
            echo "$source_line"
        } >> "$rcfile"

        chown "${MACUSER}:staff" "$rcfile" 2>/dev/null || true
        echo "  Successfully added source line to $shell_name"
    fi
}

# Creates the given shell profile file if it does not already exist, setting
# ownership and permissions appropriate for the console user.
create_rcfile_if_needed() {
    local filepath="$1"
    local shell_name="$2"

    if [ -f "${filepath}" ]; then
        echo "${shell_name} exists: ${filepath}"
    else
        echo "${shell_name} doesn't exist. Creating: ${filepath}"
        if touch "${filepath}" && chown "${MACUSER}:staff" "${filepath}" && chmod 644 "${filepath}"; then
            echo "Successfully created ${filepath}"
        else
            echo "Failed to create ${filepath}"
            return 1
        fi
    fi
    return 0
}

########################################################################################
######################### SHELL CONFIGURATION ##########################################
########################################################################################

ZSHFILE="$USERHOME/.zprofile"
BASHFILE="$USERHOME/.bash_profile"

echo "Updating shell configuration for user: $MACUSER"

# Build (or rebuild) the vars file before touching any rc files
if ! create_netskope_vars_file; then
    echo "ERROR: Failed to create .netskope_vars file"
    exit 1
fi

# Ensure both profile files exist, then inject the source line into each
if create_rcfile_if_needed "$ZSHFILE" "zprofile"; then
    add_source_to_rcfile "$ZSHFILE" "zprofile"
fi

if create_rcfile_if_needed "$BASHFILE" "bash_profile"; then
    add_source_to_rcfile "$BASHFILE" "bash_profile"
fi

echo "Shell configuration update complete"
exit 0
